[project]
name = "mymemory"
version = "0.1.0"
description = "MyMemory using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[tools]==1.3.0",
    "litellm>=1.79.1",
]

[project.scripts]
mymemory = "mymemory.main:run"
run_crew = "mymemory.main:run"
train = "mymemory.main:train"
replay = "mymemory.main:replay"
test = "mymemory.main:test"
run_with_trigger = "mymemory.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
